# Generated by Django 4.2.7 on 2023-11-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('punch_in_time', models.DateTimeField()),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
